# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        PlatformBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
            ROLE_USER:        ROLE_ETUDIANT
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        db_provider:
            entity:
                class: PlatformBundle:User
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

            #  redirrige automatique vers la page loggin apres submit du register
            #guard:
                #authenticators:
                    #- app.security.login_form_authenticator
            remember_me:
                secret: "ilsembleetredifficileàdevinerr"
                lifetime: 604800
                path:     /
                domain: ~
                name:      REMEMBERME
                always_remember_me: true
                remember_me_parameter: _remember_me
                
#            provider:
#                chain_provider:
#                    chain:
#                        providers: [in_memory, db_provider]

            form_login:
                login_path: login
                check_path: login
                remember_me: true
            logout:
                path: /logout
                target: /
                
    access_control:
       - { path: ^/not-found ,  role: IS_AUTHENTICATED_ANONYMOUSLY  }
       - { path: ^/plan-du-site , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/ , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/login$ , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/contact , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/services , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/mentions-legales , role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/bilan , role: [  ROLE_ETUDIANT,ROLE_ADMIN ,ROLE_SUPER_ADMIN ] }
       #- { path: ^/profile , role: [  ROLE_VISITOR, ROLE_ADMIN ,ROLE_SUPER_ADMIN ] }
       #- { path: ^/presentation-du-mooc/id/ ,  role: [  ROLE_VISITOR ROLE_ADMIN , ROLE_SUPER_ADMIN ] }
       #- { path: ^/mooc/id/,  role: [  ROLE_VISITOR,ROLE_ADMIN , ROLE_SUPER_ADMIN ] }
       - { path: ^/admin/, role: [  ROLE_ADMIN ,ROLE_SUPER_ADMIN ] }
       #- { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       #- { path: ^/admin/logout$, role: [  ROLE_ADMIN ,ROLE_SUPER_ADMIN ] }
       #- { path: ^/admin/login_check$, role: [  ROLE_ADMIN ,ROLE_SUPER_ADMIN ] }
       #- { path: ^/profile/\d+/edit, roles: ROLE_ETUDIANT }
       #- { path: ^/comment/\d+/edit, roles: ROLE_ETUDIANT }
